# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='manuscript_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
